name: Cartogramando
description: Hazlo fácil. Usa un mapa
meta_description: "gis, sig, mapping, leaflet, javascript, carto, postgis, spatial, webmapping, openlayers, arcgis"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
domain_name: 'http://ccabanes.github.io'
google_analytics: 'UA-68142493-1'

# Details for the RSS feed generator
url:            'http://ccabanes.github.io'
author:         'Carlos Cabanes'


# Media variables
twitter_username:     cabanescarlos
github_username:      ccabanes
linkedin_username:    cabanescarlos

#Bitly
bitly:
  username: ccabanes
  api_key: R_0213af32c0034148ada4bc8bd25ee89c

#Permalink
permalink: pretty
